DRUG_CATALOG = {
    "Dupixent": "Autoimmune",
    "Stelara": "Autoimmune",
    "Skyrizi": "Autoimmune",
    "Humira": "Autoimmune",
    "Nubeqa": "Oncology",
    "Rinvoq": "Autoimmune",
    "Rezdiffra": "Hepatology",
    "Ibrance": "Oncology",
    "Cosentyx": "Rheumatology",
    "Nemluvio": "Autoimmune",
    "Tremfya": "Autoimmune",
    "Epclusa": "Hepatology",
    "Verzenio": "Oncology",
    "Kevzara": "Autoimmune",
    "Otezla": "Autoimmune",
    "Tymlos": "Osteoporosis",
    "Ohtuvayre": "Respiratory",
    "Pomolidomide": "Oncology",
    "Fasenra": "Respiratory",
    "Jascayd": "Respiratory",
    "Austedo": "Neurology",
    "Xtandi": "Oncology",
}